name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Swift
        uses: actions/setup-swift@v1
        with:
          swift-version: '5.7'
      - name: Build
        run: swift build --configuration release
      - name: Test
        run: swift test